#
# (C) Copyright 2012
# Marvell Semiconductor <www.marvell.com>
# Written-by: Xiang Wang <wangx@marvell.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_MRVL_BOOT) += mv_boot.o
obj-$(CONFIG_GENERIC_MMC) += mv_recovery.o
